name: Weekly AI Blog Post with Blog Index

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  generate-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install openai markdown

      - name: Generate blog post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python generate_blog_post.py
          cd blog && python render_blog_posts.py
          cd ..
          python generate_blog_index.py

      - name: Commit updates
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add blog/*.md blog/*.html blog/index.html
          git commit -m "🤖 Weekly blog post + updated index" || echo "No changes"
          git push